-- migrate_v7.sql
-- 入参/出参配置升级：无限层级嵌套 + 出参传递参数来源
--
-- 本次升级不涉及数据库表结构变更。
-- ai_tool.data_params_json 和 ai_tool.response_params_json 均为 TEXT 字段存储 JSON，
-- 格式升级向下兼容，旧数据无需迁移。
--
-- 入参 JSON 格式变化说明（data_params_json）：
--   新增 valueSource 字段，取值：
--     static   - 静态值（原 valueType=static）
--     context  - 接口上下文（原 valueType=context / 用户数据，取值逻辑不变）
--     response - 出参传递（新增，由应用编排层在运行时注入，配置阶段留空）
--   Object/Array 类型参数支持无限层级嵌套 children。
--   Array 类型在运行时解析为 JSON 数组（之前解析为对象，现已修正）。
--
-- 出参 JSON 格式变化说明（response_params_json）：
--   Object/Array 类型参数支持无限层级嵌套 children（之前前端限制三级，现已去除限制）。
--
-- 如需对旧数据中 valueType 字段做标准化，可执行以下语句（可选，服务端已兼容旧格式）：
-- UPDATE ai_tool SET data_params_json = ... WHERE data_params_json LIKE '%"valueType"%';
-- （建议由业务侧按需处理，此处不强制执行）
